class Currency {
  final String _country;
  final String _symbol;

  Currency({required country, symbol})
      : _country = country,
        _symbol = symbol;

  String get country => _country;

  String get symbol => _symbol;

  static final List<Currency> currencies = [
    Currency(country: 'Afghanistan', symbol: 'AFN'),
    Currency(country: 'Albania', symbol: 'ALL'),
    Currency(country: 'Algeria', symbol: 'DZD'),
    Currency(country: 'Angola', symbol: 'AOA'),
    Currency(country: 'Argentina', symbol: 'AR\$'),
    Currency(country: 'Armenia', symbol: '֏'),
    Currency(country: 'Australia', symbol: 'AU\$'),
    Currency(country: 'Azerbaijan', symbol: '₼'),
    Currency(country: 'Bahamas', symbol: 'BS\$'),
    Currency(country: 'Bahrain', symbol: 'BHD'),
    Currency(country: 'Bangladesh', symbol: '৳'),
    Currency(country: 'Barbados', symbol: 'BBD'),
    Currency(country: 'Belarus', symbol: 'BYN'),
    Currency(country: 'Belize', symbol: 'BZ\$'),
    Currency(country: 'Benin', symbol: 'CFA'),
    Currency(country: 'Bhutan', symbol: 'BTN'),
    Currency(country: 'Bolivia', symbol: 'BOB'),
    Currency(country: 'Bosnia and Herzegovina', symbol: 'BAM'),
    Currency(country: 'Botswana', symbol: 'BWP'),
    Currency(country: 'Brazil', symbol: 'R\$'),
    Currency(country: 'Brunei', symbol: 'BND'),
    Currency(country: 'Bulgaria', symbol: 'BGN'),
    Currency(country: 'Burkina Faso', symbol: 'CFA'),
    Currency(country: 'Burundi', symbol: 'BIF'),
    Currency(country: 'Cambodia', symbol: 'KHR'),
    Currency(country: 'Cameroon', symbol: 'CFA'),
    Currency(country: 'Canada', symbol: 'CA\$'),
    Currency(country: 'Cape Verde', symbol: 'CVE'),
    Currency(country: 'Central African Republic', symbol: 'CFA'),
    Currency(country: 'Chile', symbol: 'CLP'),
    Currency(country: 'China', symbol: 'CNY'),
    Currency(country: 'Colombia', symbol: 'COP'),
    Currency(country: 'Comoros', symbol: 'KMF'),
    Currency(country: 'Congo', symbol: 'CDF'),
    Currency(country: 'Costa Rica', symbol: 'CRC'),
    Currency(country: 'Croatia', symbol: 'HRK'),
    Currency(country: 'Cuba', symbol: 'CUP'),
    Currency(country: 'Czech Republic', symbol: 'CZK'),
    Currency(country: 'Denmark', symbol: 'DKK'),
    Currency(country: 'Djibouti', symbol: 'DJF'),
    Currency(country: 'Dominican Republic', symbol: 'DOP'),
    Currency(country: 'Egypt', symbol: 'EGP'),
    Currency(country: 'Euro', symbol: '€'),
    Currency(country: 'Ethiopia', symbol: 'ETB'),
    Currency(country: 'Fiji', symbol: 'FJD'),
    Currency(country: 'Gambia', symbol: 'GMD'),
    Currency(country: 'Ghana', symbol: 'GHS'),
    Currency(country: 'Guatemala', symbol: 'GTQ'),
    Currency(country: 'Guinea', symbol: 'GNF'),
    Currency(country: 'Guyana', symbol: 'GYD'),
    Currency(country: 'Haiti', symbol: 'HTG'),
    Currency(country: 'Honduras', symbol: 'HNL'),
    Currency(country: 'Hong Kong', symbol: 'HK\$'),
    Currency(country: 'Hungary', symbol: 'HUF'),
    Currency(country: 'Iceland', symbol: 'ISK'),
    Currency(country: 'India', symbol: '₹'),
    Currency(country: 'Indonesia', symbol: 'IDR'),
    Currency(country: 'Iran', symbol: 'IRR'),
    Currency(country: 'Iraq', symbol: 'IQD'),
    Currency(country: 'Israel', symbol: '₪'),
    Currency(country: 'Jamaica', symbol: 'JMD'),
    Currency(country: 'Japan', symbol: 'JPY'),
    Currency(country: 'Jordan', symbol: 'JOD'),
    Currency(country: 'Kazakhstan', symbol: 'KZT'),
    Currency(country: 'Kenya', symbol: 'KES'),
    Currency(country: 'Kuwait', symbol: 'KWD'),
    Currency(country: 'Kyrgyzstan', symbol: 'KGS'),
    Currency(country: 'Laos', symbol: 'LAK'),
    Currency(country: 'Lebanon', symbol: 'LBP'),
    Currency(country: 'Lesotho', symbol: 'LSL'),
    Currency(country: 'Liberia', symbol: 'LRD'),
    Currency(country: 'Libya', symbol: 'LYD'),
    Currency(country: 'Madagascar', symbol: 'MGA'),
    Currency(country: 'Malawi', symbol: 'MWK'),
    Currency(country: 'Malaysia', symbol: 'MYR'),
    Currency(country: 'Maldives', symbol: 'MVR'),
    Currency(country: 'Mexico', symbol: 'MX\$'),
    Currency(country: 'Moldova', symbol: 'MDL'),
    Currency(country: 'Mongolia', symbol: 'MNT'),
    Currency(country: 'Morocco', symbol: 'dh'),
    Currency(country: 'Mozambique', symbol: 'MZN'),
    Currency(country: 'Myanmar', symbol: 'MMK'),
    Currency(country: 'Namibia', symbol: 'NAD'),
    Currency(country: 'Nepal', symbol: 'NPR'),
    Currency(country: 'New Zealand', symbol: 'NZ\$'),
    Currency(country: 'Nicaragua', symbol: 'NIO'),
    Currency(country: 'Nigeria', symbol: 'NGN'),
    Currency(country: 'Norway', symbol: 'NOK'),
    Currency(country: 'Oman', symbol: 'OMR'),
    Currency(country: 'Pakistan', symbol: 'PKR'),
    Currency(country: 'Panama', symbol: 'PAB'),
    Currency(country: 'Paraguay', symbol: 'PYG'),
    Currency(country: 'Peru', symbol: 'PEN'),
    Currency(country: 'Philippines', symbol: 'PHP'),
    Currency(country: 'Poland', symbol: 'PLN'),
    Currency(country: 'Qatar', symbol: 'QAR'),
    Currency(country: 'Russia', symbol: 'RUB'),
    Currency(country: 'Saudi Arabia', symbol: 'SAR'),
    Currency(country: 'South Africa', symbol: 'ZAR'),
    Currency(country: 'South Korea', symbol: 'KRW'),
    Currency(country: 'Sri Lanka', symbol: 'LKR'),
    Currency(country: 'Sweden', symbol: 'SEK'),
    Currency(country: 'Switzerland', symbol: 'CHF'),
    Currency(country: 'Turkey', symbol: 'TRY'),
    Currency(country: 'United Kingdom', symbol: 'GBP'),
    Currency(country: 'Us Dollar', symbol: '\$'),
    Currency(country: 'Vietnam', symbol: 'VND'),
    Currency(country: 'Zimbabwe', symbol: 'ZWL'),
  ];
}
