class Currency {
  final String _country;
  final String _symbol;

  Currency({required country, symbol})
      : _country = country,
        _symbol = symbol;

  String get country => _country;

  String get symbol => _symbol;

  // list of all world counties with their currency symbol
  static final List<Currency> currencies = [
    Currency(country: 'Afghanistan', symbol: '؋'),
    Currency(country: 'Albania', symbol: 'Lek'),
    Currency(country: 'Algeria', symbol: 'د.ج'),
    Currency(country: 'Angola', symbol: 'Kz'),
    Currency(country: 'Armenia', symbol: '֏'),
    Currency(country: 'Azerbaijan', symbol: '₼'),
    Currency(country: 'Bahamas', symbol: 'B\$'),
    Currency(country: 'Bahrain', symbol: 'BD'),
    Currency(country: 'Bangladesh', symbol: '৳'),
    Currency(country: 'Belarus', symbol: 'Br'),
    Currency(country: 'Belize', symbol: 'BZ\$'),
    Currency(country: 'Benin', symbol: 'CFA'),
    Currency(country: 'Bhutan', symbol: 'Nu.'),
    Currency(country: 'Bolivia', symbol: 'Bs.'),
    Currency(country: 'Bosnia and Herzegovina', symbol: 'KM'),
    Currency(country: 'Botswana', symbol: 'P'),
    Currency(country: 'Brazil', symbol: 'R\$'),
    Currency(country: 'Brunei', symbol: 'B\$'),
    Currency(country: 'Bulgaria', symbol: 'лв'),
    Currency(country: 'Burkina Faso', symbol: 'CFA'),
    Currency(country: 'Burundi', symbol: 'FBu'),
    Currency(country: 'Cambodia', symbol: '៛'),
    Currency(country: 'Cameroon', symbol: 'CFA'),
    Currency(country: 'Cape Verde', symbol: 'CVE'),
    Currency(country: 'Central African Republic', symbol: 'CFA'),
    Currency(country: 'China', symbol: '¥'),
    Currency(country: 'Comoros', symbol: 'KMF'),
    Currency(country: 'Congo', symbol: 'FC'),
    Currency(country: 'Costa Rica', symbol: '₡'),
    Currency(country: 'Croatia', symbol: 'kn'),
    Currency(country: 'Cuba', symbol: '₱'),
    Currency(country: 'Czech Republic', symbol: 'Kč'),
    Currency(country: 'Denmark', symbol: 'kr'),
    Currency(country: 'Djibouti', symbol: 'Fdj'),
    Currency(country: 'Dollar', symbol: '\$'),
    Currency(country: 'Dominican Republic', symbol: 'RD\$'),
    Currency(country: 'Egypt', symbol: 'E£'),
    Currency(country: 'Euro', symbol: '€'),
    Currency(country: 'Ethiopia', symbol: 'Br'),
    Currency(country: 'Gambia', symbol: 'D'),
    Currency(country: 'Ghana', symbol: 'GH₵'),
    Currency(country: 'Guatemala', symbol: 'Q'),
    Currency(country: 'Guinea', symbol: 'FG'),
    Currency(country: 'Haiti', symbol: 'G'),
    Currency(country: 'Honduras', symbol: 'L'),
    Currency(country: 'Hong Kong', symbol: 'HK\$'),
    Currency(country: 'Hungary', symbol: 'Ft'),
    Currency(country: 'Iceland', symbol: 'kr'),
    Currency(country: 'India', symbol: '₹'),
    Currency(country: 'Indonesia', symbol: 'Rp'),
    Currency(country: 'Iran', symbol: '﷼'),
    Currency(country: 'Iraq', symbol: 'ع.د'),
    Currency(country: 'Israel', symbol: '₪'),
    Currency(country: 'Japan', symbol: '¥'),
    Currency(country: 'Jordan', symbol: 'JD'),
    Currency(country: 'Kazakhstan', symbol: '₸'),
    Currency(country: 'Kenya', symbol: 'KSh'),
    Currency(country: 'Kuwait', symbol: 'KD'),
    Currency(country: 'Kyrgyzstan', symbol: 'сом'),
    Currency(country: 'Laos', symbol: '₭'),
    Currency(country: 'Lebanon', symbol: 'ل.ل'),
    Currency(country: 'Lesotho', symbol: 'L'),
    Currency(country: 'Libya', symbol: 'LD'),
    Currency(country: 'Madagascar', symbol: 'Ar'),
    Currency(country: 'Malawi', symbol: 'MK'),
    Currency(country: 'Malaysia', symbol: 'RM'),
    Currency(country: 'Maldives', symbol: 'Rf'),
    Currency(country: 'Moldova', symbol: 'L'),
    Currency(country: 'Mongolia', symbol: '₮'),
    Currency(country: 'Morocco', symbol: 'dh'),
    Currency(country: 'Mozambique', symbol: 'MT'),
    Currency(country: 'Myanmar', symbol: 'K'),
    Currency(country: 'Nepal', symbol: 'रू'),
    Currency(country: 'Nicaragua', symbol: 'C\$'),
    Currency(country: 'Nigeria', symbol: '₦'),
    Currency(country: 'Norway', symbol: 'kr'),
    Currency(country: 'Oman', symbol: 'ر.ع.'),
    Currency(country: 'Pakistan', symbol: '₨'),
    Currency(country: 'Panama', symbol: 'B/.'),
    Currency(country: 'Paraguay', symbol: '₲'),
    Currency(country: 'Peru', symbol: 'S/'),
    Currency(country: 'Philippines', symbol: '₱'),
    Currency(country: 'Poland', symbol: 'zł'),
    Currency(country: 'Qatar', symbol: 'ر.ق'),
    Currency(country: 'Russia', symbol: '₽'),
    Currency(country: 'Saudi Arabia', symbol: 'ر.س'),
    Currency(country: 'South Africa', symbol: 'R'),
    Currency(country: 'South Korea', symbol: '₩'),
    Currency(country: 'Sri Lanka', symbol: 'රු'),
    Currency(country: 'Sweden', symbol: 'kr'),
    Currency(country: 'Switzerland', symbol: 'Fr'),
    Currency(country: 'Turkey', symbol: '₺'),
    Currency(country: 'United Kingdom', symbol: '£'),
    Currency(country: 'Vietnam', symbol: '₫'),
    Currency(country: 'Zimbabwe', symbol: 'ZWL\$'),
  ];
}
